cordova plugin add   org.apache.cordova.device
cordova plugin add   https://github.com/katzer/cordova-plugin-email-composer.git
cordova plugin add   org.apache.cordova.camera
cordova plugin add   https://github.com/apache/cordova-plugin-inappbrowser.git
cordova plugin add   org.apache.cordova.statusbar
cordova plugin add   org.apache.cordova.console
cordova plugin add   org.apache.cordova.file
cordova plugin add   https://github.com/driftyco/ionic-plugins-keyboard.git
cordova plugin add   org.apache.cordova.splashscreen