CREATE TABLE `merchant_data_import_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `store_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `version_num` tinyint(4) NOT NULL,
  `merchant_id` int(11) NOT NULL,
  `merchant_name` varchar(255) NOT NULL,
  `merchant_marketplace` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `fax` varchar(100) NOT NULL,
  `address_1` varchar(255) NOT NULL,
  `address_2` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `state` varchar(50) NOT NULL,
  `zip` varchar(20) NOT NULL,
  `website` varchar(255) NOT NULL,
  `send_violation_notifications` char(1) NOT NULL,
  `notification_template` tinyint(4) NOT NULL,
  `send_to_primary` char(1) NOT NULL,
  `send_to_account_reps` char(1) NOT NULL,
  `send_to_cc_addresses` char(1) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `store_id` (`store_id`,`user_id`,`merchant_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `merchant_contact_data_import_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `store_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `version_num` tinyint(4) NOT NULL,
  `merchant_id` int(11) NOT NULL,
  `contact_id` varchar(255) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone_number` varchar(50) NOT NULL,
  `contact_type` tinyint(4) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `store_id` (`store_id`,`user_id`,`merchant_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;